version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telephone-input-app
    image: telephone-input-image
    volumes:
      - ./src/:/app/src/
    ports:
      - "3000:3000"
